# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
